/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.gs1_prototipo1.view.pages;

import com.mycompany.gs1_prototipo1.control.Control;
import com.mycompany.gs1_prototipo1.control.UIController;
import com.mycompany.gs1_prototipo1.model.LongMission;
import com.mycompany.gs1_prototipo1.model.Mission;
import com.mycompany.gs1_prototipo1.model.User;
import com.mycompany.gs1_prototipo1.model.types.Label;
import com.mycompany.gs1_prototipo1.model.types.Weekday;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author pabloantoniolopezmartin
 */
public class CRUDMissionPage extends javax.swing.JPanel {

    /**
     * Creates new form Mission
     */
    private Mission mission;
    private LongMission longMission;
    private List<Label> labels;
    private List<User>  subscribedUsers;
    private List<Weekday> days;
    
    DefaultListModel modeloSubscribers = new DefaultListModel();
    DefaultListModel modeloLabels = new DefaultListModel();
    DefaultListModel modeloAddLabels = new DefaultListModel();
    DefaultListModel modeloDays = new DefaultListModel();
    DefaultListModel modeloAddDays = new DefaultListModel();
    
    
    public CRUDMissionPage(Mission mission) {
        initComponents();
        longMission = null;
        labels = mission.getLabels();
        subscribedUsers = mission.getSubscribedUsers();
        subscribers.setModel(modeloSubscribers);
        myLabels.setModel(modeloLabels);
        labelsList.setModel(modeloAddLabels);
        this.mission=mission;
        updateMissionPage();
    }
    
    public CRUDMissionPage(LongMission longMission){
        initComponents();
        mission = null;
        labels = longMission.getLabels();
        subscribedUsers = longMission.getSubscribedUsers();
        days = longMission.getDays();
        subscribers.setModel(modeloSubscribers);
        myLabels.setModel(modeloLabels);
        labelsList.setModel(modeloAddLabels);
        myDaysList.setModel(modeloDays);
        daysList.setModel(modeloAddDays);
        this.longMission = longMission;
        updateLongMissionPage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JLayeredPane();
        titleHeader = new javax.swing.JLabel();
        body = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        title = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        endDateTitle = new javax.swing.JLabel();
        endDate = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        subscribers = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        myLabels = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        labelsList = new javax.swing.JList<>();
        deleteLabel = new javax.swing.JButton();
        addLabel = new javax.swing.JButton();
        inicialDate = new javax.swing.JTextField();
        deleteSubscriber = new javax.swing.JButton();
        save = new javax.swing.JButton();
        details = new javax.swing.JPanel();
        placeTitle = new javax.swing.JLabel();
        place = new javax.swing.JTextField();
        myDaysTitle = new javax.swing.JLabel();
        myDaysPane = new javax.swing.JScrollPane();
        myDaysList = new javax.swing.JList<>();
        daysTitle = new javax.swing.JLabel();
        daysPane = new javax.swing.JScrollPane();
        daysList = new javax.swing.JList<>();
        deleteDay = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        addDay = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(303, 608));

        titleHeader.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        titleHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleHeader.setIcon(new javax.swing.ImageIcon("C:\\Users\\esthe\\Documents\\NetBeansProjects\\GS1_PROTOTIPO1\\src\\main\\java\\com\\mycompany\\gs1_prototipo1\\media\\header1.png")); // NOI18N
        titleHeader.setText("Misión");
        titleHeader.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        header.setLayer(titleHeader, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(titleHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(177, 74, 6));
        jLabel8.setText("Título:");

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(177, 74, 6));
        jLabel2.setText("Descripción:");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        description.setBackground(new java.awt.Color(255, 255, 204));
        description.setColumns(20);
        description.setFont(new java.awt.Font("Yu Gothic", 1, 11)); // NOI18N
        description.setLineWrap(true);
        description.setRows(5);
        description.setWrapStyleWord(true);
        description.setBorder(null);
        jScrollPane1.setViewportView(description);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(177, 74, 6));
        jLabel1.setText("Inicio:");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        endDateTitle.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        endDateTitle.setForeground(new java.awt.Color(177, 74, 6));
        endDateTitle.setText("Final:");
        endDateTitle.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(177, 74, 6));
        jLabel4.setText("Categoría:");

        subscribers.setBackground(new java.awt.Color(255, 255, 204));
        subscribers.setRequestFocusEnabled(false);
        subscribers.setSelectionBackground(new java.awt.Color(246, 253, 212));
        subscribers.setSelectionForeground(new java.awt.Color(0, 0, 0));
        subscribers.setValueIsAdjusting(true);
        jScrollPane2.setViewportView(subscribers);

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(177, 74, 6));
        jLabel6.setText("Participantes:");

        myLabels.setBackground(new java.awt.Color(255, 255, 204));
        jScrollPane3.setViewportView(myLabels);

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(177, 74, 6));
        jLabel5.setText("Añadir categoría:");

        labelsList.setBackground(new java.awt.Color(255, 255, 204));
        jScrollPane4.setViewportView(labelsList);

        deleteLabel.setText("Eliminar");
        deleteLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteLabelActionPerformed(evt);
            }
        });

        addLabel.setText("Añadir");
        addLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLabelActionPerformed(evt);
            }
        });

        deleteSubscriber.setText("Eliminar");
        deleteSubscriber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteSubscriberActionPerformed(evt);
            }
        });

        save.setIcon(new javax.swing.ImageIcon("C:\\Users\\esthe\\Documents\\NetBeansProjects\\GS1_PROTOTIPO1\\src\\main\\java\\com\\mycompany\\gs1_prototipo1\\media\\tick.png")); // NOI18N
        save.setAutoscrolls(true);
        save.setFocusPainted(false);
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        placeTitle.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        placeTitle.setForeground(new java.awt.Color(177, 74, 6));
        placeTitle.setText("Lugar:");

        myDaysTitle.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        myDaysTitle.setForeground(new java.awt.Color(177, 74, 6));
        myDaysTitle.setText("Días:");

        myDaysList.setBackground(new java.awt.Color(255, 255, 204));
        myDaysPane.setViewportView(myDaysList);

        daysTitle.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        daysTitle.setForeground(new java.awt.Color(177, 74, 6));
        daysTitle.setText("Añadir días:");

        daysList.setBackground(new java.awt.Color(255, 255, 204));
        daysPane.setViewportView(daysList);

        deleteDay.setText("Eliminar");
        deleteDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteDayActionPerformed(evt);
            }
        });

        addDay.setText("Añadir");
        addDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout detailsLayout = new javax.swing.GroupLayout(details);
        details.setLayout(detailsLayout);
        detailsLayout.setHorizontalGroup(
            detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailsLayout.createSequentialGroup()
                .addGroup(detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(detailsLayout.createSequentialGroup()
                        .addComponent(placeTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(place, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(detailsLayout.createSequentialGroup()
                        .addGroup(detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(myDaysTitle)
                            .addComponent(deleteDay, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(myDaysPane, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(detailsLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(addDay, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detailsLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(daysTitle)
                                    .addComponent(daysPane, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jSeparator1))
                .addContainerGap())
        );
        detailsLayout.setVerticalGroup(
            detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailsLayout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(placeTitle)
                    .addComponent(place, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(myDaysTitle)
                    .addComponent(daysTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(myDaysPane, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(daysPane, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteDay)
                    .addComponent(addDay)))
        );

        javax.swing.GroupLayout bodyLayout = new javax.swing.GroupLayout(body);
        body.setLayout(bodyLayout);
        bodyLayout.setHorizontalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(details, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(bodyLayout.createSequentialGroup()
                        .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2)
                                .addComponent(jSeparator3)
                                .addComponent(jLabel6)
                                .addGroup(bodyLayout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(inicialDate, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(12, 12, 12)
                                    .addComponent(endDateTitle)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(endDate, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(bodyLayout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(save))
                                .addComponent(jScrollPane1)
                                .addGroup(bodyLayout.createSequentialGroup()
                                    .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(deleteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(addLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)))))
                            .addGroup(bodyLayout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deleteSubscriber)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        bodyLayout.setVerticalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyLayout.createSequentialGroup()
                .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(bodyLayout.createSequentialGroup()
                        .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(inicialDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endDateTitle)
                    .addComponent(endDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteLabel)
                    .addComponent(addLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteSubscriber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(details, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(body, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deleteLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteLabelActionPerformed
        List<Label> deleteLabels = new ArrayList<>();
        int[] selectedIndices = myLabels.getSelectedIndices();
        for (int index : selectedIndices) {
            deleteLabels.add((Label) modeloLabels.getElementAt(index));
        }
        if(!deleteLabels.isEmpty()){
            List<Label> eliminarLabels = new ArrayList<>();
            for (Label label : labels) {
                for (Label eliminarLabel : deleteLabels) {
                    if(label.equals(eliminarLabel)){
                        eliminarLabels.add(label);
                        modeloLabels.removeElement(eliminarLabel);
                        break;
                    }
                }
            }
            if(!eliminarLabels.isEmpty()){
                labels.removeAll(eliminarLabels);
            }
        }
    }//GEN-LAST:event_deleteLabelActionPerformed

    private void addLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLabelActionPerformed
        List<Label> addLabels = new ArrayList<>();
        int[] selectedIndices = labelsList.getSelectedIndices();
        for (int index : selectedIndices) {
            addLabels.add((Label) modeloAddLabels.getElementAt(index));
        }
        if(!addLabels.isEmpty()){
            boolean add = true;
            for (Label añadirLabel : addLabels) {
                for (Label label : labels) {
                    if(label.equals(añadirLabel)){
                        add = false;
                        break;
                    }
                }
                if(add){
                    labels.add(añadirLabel);
                    modeloLabels.addElement(añadirLabel);
                }else{
                    add = true;
                }
            }
        }
    }//GEN-LAST:event_addLabelActionPerformed

    private void deleteSubscriberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteSubscriberActionPerformed
        List<String> deteleUser = new ArrayList<>();
        int[] selectedIndices = subscribers.getSelectedIndices();
        for (int index : selectedIndices) {
            deteleUser.add((String) modeloSubscribers.getElementAt(index));
        }
        if(!modeloSubscribers.isEmpty()){
            int answer = JOptionPane.showConfirmDialog(this, "¿Quiere eliminar los suscriptores seleccionados?", "Salir", JOptionPane.YES_NO_OPTION);
            if(answer == JOptionPane.YES_OPTION){
                List<User> eliminarUser = new ArrayList<>();
                for (User user : subscribedUsers) {
                    for (String deleteUser : deteleUser) {
                        if(user.getName().equals(deleteUser)){
                            eliminarUser.add(user);
                            modeloSubscribers.removeElement(deleteUser);
                            break;
                        }
                    }
                }
                if(!eliminarUser.isEmpty()){
                    subscribedUsers.removeAll(eliminarUser);
                }
            }
        }
    }//GEN-LAST:event_deleteSubscriberActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        if(title.getText().isBlank()){
            JOptionPane.showMessageDialog(this, "No puede dejar el Título en blanco", "Campo obligatorio", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if(description.getText().isBlank()){
            JOptionPane.showMessageDialog(this, "No puede dejar la Descripción en blanco", "Campo obligatorio", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if(inicialDate.getText().isBlank() || endDate.getText().isBlank()){
            JOptionPane.showMessageDialog(this, "No puede dejar ninguna fecha en blanco", "Campo obligatorio", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if(modeloLabels.isEmpty()){
            JOptionPane.showMessageDialog(this, "Tiene que tener al menos una categoría", "Campo obligatorio", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if(place.getText().isBlank()){
            JOptionPane.showMessageDialog(this, "No puede dejar el Lugar en blanco", "Campo obligatorio", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if(modeloDays.isEmpty()){
            JOptionPane.showMessageDialog(this, "Tiene que tener al menos un día", "Campo obligatorio", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if(longMission != null){
            longMission.setLabels(labels);
            longMission.setSubscribedUsers(subscribedUsers);
            longMission.setDescription(description.getText());
            longMission.setTitle(title.getText());
            if(longMission.getInPerson()){
                longMission.getLocation().setCity(place.getText());
            }
            try{
                DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
                Date starDate = dateFormat.parse(inicialDate.getText());
                Date finalDate = dateFormat.parse(endDate.getText());
                //validar fecha;
                longMission.setStartDate(starDate);
                longMission.setEndDate(finalDate);
                int newDuration=(int) ((finalDate.getTime()-starDate.getTime())/86400000);
                longMission.setDuration(newDuration);
            }catch (Exception e){
                JOptionPane.showMessageDialog(this, "La fecha tiene que estar en el formato d/m/yyyy", "Campo obligatorio", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
        }else{
            mission.setLabels(labels);
            mission.setSubscribedUsers(subscribedUsers);
            mission.setDescription(description.getText());
            mission.setTitle(title.getText());
            if(mission.getInPerson()) mission.getLocation().setCity(place.getText());
            try{
                DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
                Date starDate = dateFormat.parse(inicialDate.getText());
                Date finalDate = dateFormat.parse(endDate.getText());
                //validar fecha;
                mission.setStartDate(starDate);
                mission.setEndDate(finalDate);
                
            }catch (Exception e){
                JOptionPane.showMessageDialog(this, "La fecha tiene que estar en el formato d/m/yyyy", "Campo obligatorio", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
        }
        JOptionPane.showMessageDialog(this, "Los cambios se han guardado correctamente", "Guardado", JOptionPane.INFORMATION_MESSAGE);
        UIController uiController = Control.getUiController();
        if(mission != null){
            //Control.getInstance().getUiController().setPersonalMission(mission.getOwner());
        }else{
           //Control.getInstance().getUiController().setPersonalMission(longMission.getOwner());
        }
        this.setVisible(false);
        this.setEnabled(false);
        Control.getInstance().getUiController().setPage("PersonalMission");
    }//GEN-LAST:event_saveActionPerformed

    private void deleteDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteDayActionPerformed
        List<Weekday> deleteDays = new ArrayList<>();
        int[] selectedIndices = myDaysList.getSelectedIndices();
        for (int index : selectedIndices) {
            deleteDays.add((Weekday) modeloDays.getElementAt(index));
        }
        if(!deleteDays.isEmpty()){
            List<Weekday> eliminarDays = new ArrayList<>();
            for (Weekday day : days) {
                for (Weekday eliminarDay : deleteDays) {
                    if(day.equals(eliminarDay)){
                        eliminarDays.add(day);
                        modeloDays.removeElement(eliminarDay);
                        break;
                    }
                }
            }
            if(!eliminarDays.isEmpty()){
                days.removeAll(eliminarDays);
            }
        }
    }//GEN-LAST:event_deleteDayActionPerformed

    private void addDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDayActionPerformed
        List<Weekday> addDays = new ArrayList<>();
        int[] selectedIndices = daysList.getSelectedIndices();
        for (int index : selectedIndices) {
            addDays.add((Weekday) modeloAddDays.getElementAt(index));
        }
        if(!addDays.isEmpty()){
            boolean add = true;
            for (Weekday añadirDay : addDays) {
                for (Weekday day : days) {
                    if(day.equals(añadirDay)){
                        add = false;
                        break;
                    }
                }
                if(add){
                    days.add(añadirDay);
                    modeloDays.addElement(añadirDay);
                }else{
                    add = true;
                }
            }
        }
    }//GEN-LAST:event_addDayActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDay;
    private javax.swing.JButton addLabel;
    private javax.swing.JPanel body;
    private javax.swing.JList<String> daysList;
    private javax.swing.JScrollPane daysPane;
    private javax.swing.JLabel daysTitle;
    private javax.swing.JButton deleteDay;
    private javax.swing.JButton deleteLabel;
    private javax.swing.JButton deleteSubscriber;
    private javax.swing.JTextArea description;
    private javax.swing.JPanel details;
    private javax.swing.JTextField endDate;
    private javax.swing.JLabel endDateTitle;
    private javax.swing.JLayeredPane header;
    private javax.swing.JTextField inicialDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JList<String> labelsList;
    private javax.swing.JList<String> myDaysList;
    private javax.swing.JScrollPane myDaysPane;
    private javax.swing.JLabel myDaysTitle;
    private javax.swing.JList<String> myLabels;
    private javax.swing.JTextField place;
    private javax.swing.JLabel placeTitle;
    private javax.swing.JButton save;
    private javax.swing.JList<String> subscribers;
    private javax.swing.JTextField title;
    private javax.swing.JLabel titleHeader;
    // End of variables declaration//GEN-END:variables

    private void updateMissionPage() {
        title.setText(mission.getTitle());
        description.setText(mission.getDescription());
        String startDate = new SimpleDateFormat("dd/MM/yyyy").format(mission.getStartDate());
        inicialDate.setText(startDate);
        String finalDate = new SimpleDateFormat("dd/MM/yyyy").format(mission.getEndDate());
        endDate.setText(finalDate);
        details.removeAll();
        if(!mission.getInPerson()){
            disableDetails(0);
        }else{
            activateDetails(1);
            disableDetails(2);
            place.setText(mission.getLocation().getCity());
        }
        
        for (Label label : Label.values()) {
            modeloAddLabels.addElement(label);
        }
        modeloLabels.removeAllElements();
        if(!mission.getLabels().isEmpty()){
            for (Label label : mission.getLabels()) {
                modeloLabels.addElement(label);
            }
        }
        myLabels.setModel(modeloLabels);
        modeloSubscribers.removeAllElements();
        if(!mission.getSubscribedUsers().isEmpty()){
            for (User subscribedUser : mission.getSubscribedUsers()) {
                modeloSubscribers.addElement(subscribedUser.getName());
            }
        }
        subscribers.setModel(modeloSubscribers);
    }

    
    private void updateLongMissionPage() {
        title.setText(longMission.getTitle());
        description.setText(longMission.getDescription());
        String startDate = new SimpleDateFormat("dd/MM/yyyy").format(longMission.getStartDate());
        inicialDate.setText(startDate);
        String finalDate = new SimpleDateFormat("dd/MM/yyyy").format(longMission.getEndDate());
        endDate.setText(finalDate);
        details.removeAll();
        if(!longMission.getInPerson()){
            disableDetails(1);
            activateDetails(2);
        }else{
            activateDetails(0);
            place.setText(longMission.getLocation().getCity());
        }
        modeloDays.removeAllElements();
        if(!longMission.getLabels().isEmpty()){
            for (Weekday day : longMission.getDays()) {
                modeloDays.addElement((Weekday) day);
            }
        }
        for (Label label : Label.values()) {
            modeloAddLabels.addElement(label);
        }
        myDaysList.setModel(modeloDays);
        modeloAddDays.removeAllElements();
        if(!longMission.getDays().isEmpty()){
            for (Weekday day : Weekday.values()) {
                modeloAddDays.addElement((Weekday) day);
            }
        }
        daysList.setModel(modeloAddDays);
        modeloLabels.removeAllElements();
        if(!longMission.getLabels().isEmpty()){
            for (Label label : longMission.getLabels()) {
                modeloLabels.addElement(label);
            }
        }
        myLabels.setModel(modeloLabels);
        modeloSubscribers.removeAllElements();
        if(!longMission.getSubscribedUsers().isEmpty()){
            for (User subscribedUser : longMission.getSubscribedUsers()) {
                modeloSubscribers.addElement( subscribedUser.getName());
            }
        }
        subscribers.setModel(modeloSubscribers);
    }

    private void disableDetails(int disable) {
        
        switch(disable){
            case 1:
                place.setVisible(false);
                placeTitle.setVisible(false);
                place.setEnabled(false);
                placeTitle.setEnabled(false);
                break;
            case 2:
                myDaysTitle.setVisible(false);
                myDaysPane.setVisible(false);
                myDaysList.setVisible(false);
                daysPane.setVisible(false);
                daysTitle.setVisible(false);
                daysList.setVisible(false);
                addDay.setVisible(false);
                deleteDay.setVisible(false);
                myDaysList.setEnabled(false);
                myDaysTitle.setEnabled(false);
                myDaysPane.setEnabled(false);
                daysTitle.setEnabled(false);
                daysPane.setEnabled(false);
                daysList.setEnabled(false);
                addDay.setEnabled(false);
                deleteDay.setEnabled(false);
                break;
            default:
                place.setVisible(false);
                placeTitle.setVisible(false);
                place.setEnabled(false);
                myDaysTitle.setVisible(false);
                myDaysPane.setVisible(false);
                myDaysList.setVisible(false);
                daysTitle.setVisible(false);
                daysPane.setVisible(false);
                daysList.setVisible(false);
                addDay.setVisible(false);
                deleteDay.setVisible(false);
                place.setEnabled(false);
                placeTitle.setEnabled(false);
                myDaysList.setEnabled(false);
                myDaysTitle.setEnabled(false);
                myDaysPane.setEnabled(false);
                daysTitle.setEnabled(false);
                daysPane.setEnabled(false);
                daysList.setEnabled(false);
                addDay.setEnabled(false);
                deleteDay.setEnabled(false);
                break;
        }
    }

    private void activateDetails(int activate) {
       
        switch(activate){
            case 1:
                place.setVisible(true);
                placeTitle.setVisible(true);
                place.setEnabled(true);
                placeTitle.setEnabled(true);
                break;
            case 2:
                myDaysTitle.setVisible(true);
                myDaysPane.setVisible(true);
                myDaysList.setVisible(true);
                daysPane.setVisible(true);
                daysTitle.setVisible(true);
                daysList.setVisible(true);
                addDay.setVisible(true);
                deleteDay.setVisible(true);
                myDaysList.setEnabled(true);
                myDaysTitle.setEnabled(true);
                myDaysPane.setEnabled(true);
                daysTitle.setEnabled(true);
                daysPane.setEnabled(true);
                daysList.setEnabled(true);
                addDay.setEnabled(true);
                deleteDay.setEnabled(true);
                break;
            default:
                place.setVisible(true);
                placeTitle.setVisible(true);
                place.setEnabled(true);
                myDaysTitle.setVisible(true);
                myDaysPane.setVisible(true);
                myDaysList.setVisible(true);
                daysTitle.setVisible(true);
                daysPane.setVisible(true);
                daysList.setVisible(true);
                addDay.setVisible(true);
                deleteDay.setVisible(true);
                place.setEnabled(true);
                placeTitle.setEnabled(true);
                myDaysList.setEnabled(true);
                myDaysTitle.setEnabled(true);
                myDaysPane.setEnabled(true);
                daysTitle.setEnabled(true);
                daysPane.setEnabled(true);
                daysList.setEnabled(true);
                addDay.setEnabled(true);
                deleteDay.setEnabled(true);
                break;
        }
    }

    
}
