/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.gs1_prototipo1.view;

import com.mycompany.gs1_prototipo1.control.Control;
import com.mycompany.gs1_prototipo1.view.pages.PersonalProfile;
import com.mycompany.gs1_prototipo1.view.pages.Login;
import java.awt.Component;
import java.awt.Dimension;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BoxLayout;
import javax.swing.JInternalFrame;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.ScrollPaneConstants;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author pabloantoniolopezmartin
 */
public class MainFrame extends javax.swing.JFrame {

    public static void setPage() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    private final Control control;

    /**
     * He creado una clase Abstracta para cubrir todas las posibles ventanas de la apliación
     * con uan interfaz genérica
     */
    
    public MainFrame() {
        initComponents();
        control = Control.getInstance();
        scrollPane.getVerticalScrollBar().setPreferredSize(new Dimension(0,0));
        scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
    
       
    }
    public void setPage(JPanel pane){
        System.out.println("a");
        displayPagePane.removeAll();
        displayPagePane.setLayout(new BoxLayout(displayPagePane, BoxLayout.PAGE_AXIS));
        Component[] components = buttonsPane.getComponents();
        if(pane instanceof Login) {
            for (Component component : components) {
                component.setVisible(false);
            }
        }else{
            for (Component component : components) {
                component.setVisible(true);
            }
        }
        displayPagePane.add(pane);
        displayPagePane.setPreferredSize(new Dimension(303, 1000));
        scrollPane.setVisible(true);
        displayPagePane.repaint();
        pack();
        System.out.println("b "+ pane.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonsPane = new javax.swing.JPanel();
        homeIco = new javax.swing.JLabel();
        profileIco = new javax.swing.JLabel();
        ladderIco = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        displayPagePane = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(238, 237, 237));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));

        buttonsPane.setBackground(new java.awt.Color(255, 255, 204));
        buttonsPane.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(231, 231, 179), 2, true));
        buttonsPane.setForeground(new java.awt.Color(255, 255, 204));
        buttonsPane.setMinimumSize(new java.awt.Dimension(229, 70));

        homeIco.setIcon(new javax.swing.ImageIcon("C:\\Users\\AZAEL\\OneDrive\\Documentos\\NetBeansProjects\\GS1_PROTOTIPO1\\src\\main\\java\\com\\mycompany\\gs1_prototipo1\\media\\icons8-home-50.png")); // NOI18N
        homeIco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeIcoMouseClicked(evt);
            }
        });

        profileIco.setIcon(new javax.swing.ImageIcon("C:\\Users\\AZAEL\\OneDrive\\Documentos\\NetBeansProjects\\GS1_PROTOTIPO1\\src\\main\\java\\com\\mycompany\\gs1_prototipo1\\media\\icons8-user-male-60.png")); // NOI18N
        profileIco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileIcoMouseClicked(evt);
            }
        });

        ladderIco.setIcon(new javax.swing.ImageIcon("C:\\Users\\AZAEL\\OneDrive\\Documentos\\NetBeansProjects\\GS1_PROTOTIPO1\\src\\main\\java\\com\\mycompany\\gs1_prototipo1\\media\\icons8-trophy-60.png")); // NOI18N

        javax.swing.GroupLayout buttonsPaneLayout = new javax.swing.GroupLayout(buttonsPane);
        buttonsPane.setLayout(buttonsPaneLayout);
        buttonsPaneLayout.setHorizontalGroup(
            buttonsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonsPaneLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(ladderIco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(homeIco)
                .addGap(62, 62, 62)
                .addComponent(profileIco)
                .addGap(32, 32, 32))
        );
        buttonsPaneLayout.setVerticalGroup(
            buttonsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homeIco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ladderIco, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
            .addComponent(profileIco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        scrollPane.setPreferredSize(new java.awt.Dimension(303, 608));

        displayPagePane.setPreferredSize(new java.awt.Dimension(303, 608));

        javax.swing.GroupLayout displayPagePaneLayout = new javax.swing.GroupLayout(displayPagePane);
        displayPagePane.setLayout(displayPagePaneLayout);
        displayPagePaneLayout.setHorizontalGroup(
            displayPagePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 303, Short.MAX_VALUE)
        );
        displayPagePaneLayout.setVerticalGroup(
            displayPagePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 608, Short.MAX_VALUE)
        );

        scrollPane.setViewportView(displayPagePane);

        //scrollPane.setVerticalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonsPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(buttonsPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void profileIcoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileIcoMouseClicked
        control.getUiController().setPersonalProfile(control.getLoggedUser());
        
    }//GEN-LAST:event_profileIcoMouseClicked

    private void homeIcoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeIcoMouseClicked
        control.getUiController().setPage("Catalog");
    }//GEN-LAST:event_homeIcoMouseClicked

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonsPane;
    private javax.swing.JPanel displayPagePane;
    private javax.swing.JLabel homeIco;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel ladderIco;
    private javax.swing.JLabel profileIco;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables
}
